# netlify.toml
[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.17.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
